#!/bin/bash
# Wrapper for doing FreeSurfer recon-all on subjects.

if [[ -z "$@" ]]
then
	echo ""
	echo "Use as: ./NatMEG_recon [megID] [T1-sequence-name] [out_dir] [subid(if not same as megID)]"
	echo "	[megID] : Sting to identify subject"
	echo "	[T1-sequence-name] : string to identify the MRI sequence"
	echo " 	[out_dir] : output directory (will use default SUBJECT_DIR if nothing is selected)."
	echo " 	[subid] : A string to rename subject in output dir. Will megID if nothing declared."
	echo ""
	exit 1
fi

# --------------------------- #
megId=$1
t1_nr=$2
if [ $4 ]; then
	export SUBJECT="$4"
else
	export SUBJECT="$1"
fi
echo "MEG id = $megId, MR seq. = $t1_nr, fs output id = $SUBJECT"

# Define output dir
if [[ ! -z "$3" ]]; then
	export SUBJECTS_DIR="$3"	
elif [ -n $SUBJECTS_DIR ]; then
	echo "Warning OUT_DIR not set. Use SUBJECTS_DIR from enviromen: $SUBJECTS_DIR"
	read -rsp "[press SPACE to confirm or anything else to cancel]" -n1 ans
	if [ ! $ans = ' ' ]; then
		echo ''
		exit 1
	fi
else
	echo "Warning OUT_DIR not set and found no SUBJECTS_DIR. Will put output in current dir: $(pwd)"
	export SUBJECTS_DIR="$(pwd)"
	read -rsp "[press SPACE to confirm or anything else to cancel]" -n1 ans
	if [ ! $ans = ' ' ]; then
		echo ''
		exit 1
	fi
fi

# --------------------------- #
export FREESURFER_HOME=/opt/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
echo "Subjects dir : $SUBJECTS_DIR"
MRI_archive='/archive/50001_MR_archive'

# Find subject 
MRI_subDir=$(find $MRI_archive -maxdepth 1 -type d -name "*$megId*" | awk 'NR==1')
#echo $MRI_subDir
if [ ! -d "$MRI_subDir" ]; then
	echo "Could not find subject "$SUBJECT" in $MRI_archive"
	exit 1
fi

# Find a dicom file
#dcmPath="$MRI_subDir/0000000$t1_nr"
dcmPath=$(find $MRI_subDir -maxdepth 1 -type d -name "*$t1_nr" | awk 'NR==1')

if [ -d "$dcmPath" ]; then 
	echo "Reading files from $dcmPath"
	export fname=$(find $dcmPath -maxdepth 1 -type f -name "*001.dcm" | awk 'NR==1')
else
	echo '-------------- Not right path! Try again --------------------'
	if [ -z "$2" ]; then
		echo "Hint: You are missing MR sequence as argument"
		ls $MRI_subDir
	fi
	ls $MRI_archive
	exit 1
fi

# Run Freesurfer 
echo '------------------------------------------------------------'
echo "---------- Now running recon-all on $SUBJECT -----------------"
echo '------------------------------------------------------------'

###### Run Freesurfer ######
recon-all -subjid $SUBJECT -i $fname -all

echo '------------------------------------------------------------'
echo "------------------- DONE $SUBJECT --------------------------"
echo '------------------------------------------------------------'

cd $SUBJECTS_DIR/$SUBJECT/mri

#END
